# 客户端配置文件

# 服务器配置
server:
  url: "http://localhost:8000"           # 服务器地址
  websocket_url: "ws://localhost:8000"   # WebSocket地址
  api_version: "v1"                       # API版本

# 客户端配置
client:
  agent_id: "agent_001"                   # 客户端ID（唯一标识）
  api_key: "your-api-key-here"            # API密钥
  name: "客服001号"                        # 客户端名称

# 微信配置
wechat:
  auto_start: true                        # 是否自动启动微信
  check_interval: 1                       # 消息检查间隔（秒）
  # 版本选择策略
  version_strategy: "auto"                # auto, plus, open_source
  prefer_plus: true                       # 是否优先使用Plus版
  fallback_enabled: true                  # 是否允许降级
  whitelisted_groups:                     # ✅ 添加：白名单群聊列表
    - 技术支持群
    - VIP客户群
    - 测试群
  
# 缓存配置
cache:
  enabled: true                           # 是否启用本地缓存
  directory: "client_cache"               # 缓存目录
  encryption: true                        # 是否加密
  cleanup_days: 7                         # 缓存保留天数

# 离线队列配置
offline_queue:
  enabled: true                           # 是否启用离线队列
  max_size: 1000                          # 最大队列长度
  retry_times: 3                          # 重试次数
  retry_interval: 60                      # 重试间隔（秒）

# 心跳配置
heartbeat:
  enabled: true                           # 是否启用心跳
  interval: 30                            # 心跳间隔（秒）
  timeout: 10                             # 心跳超时（秒）

# 日志配置
logging:
  level: "INFO"                           # 日志级别
  file: "logs/client.log"                 # 日志文件
  max_size: 10485760                      # 最大10MB
  backup_count: 5                         # 保留5个备份

# 本地简单应答配置（可选）
local_responses:
  enabled: true                           # 是否启用本地应答
  patterns:
    - pattern: "^你好$|^您好$|^hi$|^hello$"
      response: "您好！有什么可以帮您的吗？"
    - pattern: "^谢谢$|^感谢$"
      response: "不客气，很高兴能帮到您！"

