version: '3.8'

services:
  # 后端服务
  backend:
    build:
      context: ../backend
      dockerfile: ../docker/backend.Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      # 向量数据库配置（使用Supabase pgvector）
      - VECTOR_TYPE=supabase_pgvector
      - VECTOR_TABLE_NAME=${VECTOR_TABLE_NAME:-knowledge_vectors}
      - VECTOR_DIMENSION=${VECTOR_DIMENSION:-1536}
      - VECTOR_DISTANCE_METRIC=${VECTOR_DISTANCE_METRIC:-cosine}
      - VECTOR_SIMILARITY_THRESHOLD=${VECTOR_SIMILARITY_THRESHOLD:-0.7}
      - VECTOR_INDEX_TYPE=${VECTOR_INDEX_TYPE:-ivfflat}
      # AI模型配置
      - QWEN_API_KEY=${QWEN_API_KEY}
      - GLM_API_KEY=${GLM_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
    volumes:
      - ../backend/logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 前端服务
  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/frontend.Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 微信客户端（可选）
  client:
    build:
      context: ../client-new
      dockerfile: ../docker/client.Dockerfile
    environment:
      - SERVER_URL=http://backend:8000
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
    depends_on:
      - backend
    restart: unless-stopped
    volumes:
      - /dev/shm:/dev/shm  # 共享内存，用于微信自动化
    privileged: true  # 需要特权模式进行UI自动化

networks:
  default:
    name: wxauto-network
